Repository jobbole/translation-project, pull requests merged in 2018-08, with the labels that each got.

#56 #35 non obvious possibilities of python syntax 鲜为人知的python语法
  translation/Non-obvious-possibilities-of-python-syntax-鲜为人知的python语法.md
Labels: B3-Need review

#59 #36 iteration over java collections with high performance
  translation/Iteration-Over-Java-Collections-With-High-Performance.md
Labels: C1-Finished

#67 #51 leveraging lambda expressions for lazy evaluation in java
  translation/2018-08-06--51-leveraging-lambda-expressions-for-lazy-evaluation-in-java.md
Labels: C1-Finished

#71 #52 泪流满面的 11 个 git 面试题
  translation/泪流满面的 11 个 Git 面试题.md
Labels: B4-Reviewing

#72 #54 java面试 投行的15个多线程和并发面试题
  translation/Java 面试：投行的 15 个多线程和并发面试题.md
Labels: C1-Finished

#70 MODERN C++ FOR C PROGRAMMERS-PART-1
  translation/MODERN C++ FOR C PROGRAMMERS-PART 1.md
Labels: C1-Finished

#76 #29 9 best practices to handle exceptions in java
  translation/Java异常处理的9个最佳实践.md
Labels: C1-Finished

#75 #13 a comedy of errors. debugging java memory leaks
  translation/#13-A-comedy-of-errors.-Debugging-Java-memory-leaks.md
Labels: B4-Reviewing
